services:
  - type: web
    name: summabrowse
    env: python
    region: oregon
    build:
      dockerfile: Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: "2"
      - key: GUNICORN_CMD_ARGS
        value: "--workers=2 --threads=2"
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    numInstances: 1
    env: python3.10
    disk:
      name: summabrowse-disk
      mountPath: /app/uploads
      sizeGB: 1